### PR TITLE
Fix#391

### LINKED ISSUE #391: GRIB Driver breaks when built on GDAL 3.4
WHen MDAL is built on GDAL 3.4 - the GRIB tests fail with the following message

`
11: C:\Users\runes\Documents\GitHub\MDAL\tests\test_gdal_grib.cpp(214): error: Expected equality of these values:
11:   -0.818756103515625
11:   value
11:     Which is: -0.535552978515625
`
This is consistent across all platforms that I have tried.

I believe that this might be related to  https://github.com/OSGeo/gdal/issues/4524 since - if you run gdalinfo on the test GRIB file you get different results for different versions of GDAL - note the origin and corner coordinates. I do not know enough about the GRIB driver to know what effect this change would have.

IN 3.3.3 you get
`
Warning: Inside GRIB2Inventory, Message # 3
ERROR: Couldn't find 'GRIB' or 'TDLP'
Driver: GRIB/GRIdded Binary (.grb, .grb2)
Files: wind_only_u_component.grib
Size is 480, 241
Coordinate System is:
GEOGCRS["Coordinate System imported from GRIB file",
    DATUM["unnamed",
        ELLIPSOID["Sphere",6367470,0,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433,
            ID["EPSG",9122]]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 2,1
Origin = (-0.375000000000000,90.375000000000000)
Pixel Size = (0.750000000000000,-0.750000000000000)
Corner Coordinates:
Upper Left  (  -0.3750000,  90.3750000) (  0d22'30.00"W, 90d22'30.00"N)
Lower Left  (  -0.3750000, -90.3750000) (  0d22'30.00"W, 90d22'30.00"S)
Upper Right (     359.625,      90.375) (359d37'30.00"E, 90d22'30.00"N)
Lower Right (     359.625,     -90.375) (359d37'30.00"E, 90d22'30.00"S)
Center      ( 179.6250000,   0.0000000) (179d37'30.00"E,  0d 0' 0.01"N)
Band 1 Block=480x1 Type=Float64, ColorInterp=Undefined
  Description = 0[-] SFC (Ground or water surface)
  Metadata:
    GRIB_COMMENT=10 metre u wind component [m/s]
    GRIB_ELEMENT=10U
    GRIB_FORECAST_SECONDS=43200 sec
    GRIB_REF_TIME=  1538352000 sec UTC
    GRIB_SHORT_NAME=0-SFC
    GRIB_UNIT=[m/s]
    GRIB_VALID_TIME=  1538395200 sec UTC
Band 2 Block=480x1 Type=Float64, ColorInterp=Undefined
  Description = 0[-] SFC (Ground or water surface)
  Metadata:
    GRIB_COMMENT=10 metre u wind component [m/s]
    GRIB_ELEMENT=10U
    GRIB_FORECAST_SECONDS=43200 sec
    GRIB_REF_TIME=  1538395200 sec UTC
    GRIB_SHORT_NAME=0-SFC
    GRIB_UNIT=[m/s]
    GRIB_VALID_TIME=  1538438400 sec UTC
`
In 3.4 you get
`
Warning: Inside GRIB2Inventory, Message # 3
ERROR: Couldn't find 'GRIB' or 'TDLP'
Driver: GRIB/GRIdded Binary (.grb, .grb2)
Files: wind_only_u_component.grib
Size is 480, 241
Coordinate System is:
GEOGCRS["Coordinate System imported from GRIB file",
    DATUM["unnamed",
        ELLIPSOID["Sphere",6367470,0,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433,
            ID["EPSG",9122]]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 2,1
Origin = (-180.375000000000000,90.375000000000000)
Pixel Size = (0.750000000000000,-0.750000000000000)
Corner Coordinates:
Upper Left  (-180.3750000,  90.3750000) (180d22'30.00"W, 90d22'30.00"N)
Lower Left  (-180.3750000, -90.3750000) (180d22'30.00"W, 90d22'30.00"S)
Upper Right ( 179.6250000,  90.3750000) (179d37'30.00"E, 90d22'30.00"N)
Lower Right ( 179.6250000, -90.3750000) (179d37'30.00"E, 90d22'30.00"S)
Center      (  -0.3750000,   0.0000000) (  0d22'30.00"W,  0d 0' 0.01"N)
Band 1 Block=480x1 Type=Float64, ColorInterp=Undefined
  Description = 0[-] SFC (Ground or water surface)
  Metadata:
    GRIB_COMMENT=10 metre u wind component [m/s]
    GRIB_ELEMENT=10U
    GRIB_FORECAST_SECONDS=43200
    GRIB_REF_TIME=1538352000
    GRIB_SHORT_NAME=0-SFC
    GRIB_UNIT=[m/s]
    GRIB_VALID_TIME=1538395200
Band 2 Block=480x1 Type=Float64, ColorInterp=Undefined
  Description = 0[-] SFC (Ground or water surface)
  Metadata:
    GRIB_COMMENT=10 metre u wind component [m/s]
    GRIB_ELEMENT=10U
    GRIB_FORECAST_SECONDS=43200
    GRIB_REF_TIME=1538395200
    GRIB_SHORT_NAME=0-SFC
    GRIB_UNIT=[m/s]
    GRIB_VALID_TIME=1538438400
`

### PR DESCRIPTION
**Pull request by vcloarec**
Time to go ahead with GDAL >=3.4, and test using ubuntu latest

For windows, tests are done after loading dependencies from OSGEO instead of chocolatey.

For macos, not sure GDAL >=3.4 is easily available (@PeterPetrik ?), sor for now macos still uses old version.

These changes lead to drop the test coverage (-0.6), so some works are done to make this coverage increase.

fix #391

### CODE REVIEW

**Comment by runette** [comment]
> 
> For macos, not sure GDAL >=3.4 is easily available (@PeterPetrik ?), sor for now macos still uses old version.
> 

Not sure what that means?

GDAL 3.4,x, 3.5.x and 3.6.x are all available on Macos

**Comment by vcloarec** [comment]
> GDAL 3.4,x, 3.5.x and 3.6.x are all available on Macos

Good to know. I am no aware about mac stuff...
But for CI tests, here, it seems we use QGIS dependencies : https://github.com/lutraconsulting/MDAL/blob/c871d3a2a61ac5117c9a0020eae5f62407145b4e/.github/workflows/osx_tests.yml#L15
I tried with the latest version of this, but it not seems to work well. 
Maybe there are some better ways to have the gdal lib for Macos, but, for now, the more straightforward is to continue to use this old way.

**Comment by PeterPetrik** [comment]
the qgis-deps-0.9  is currently used for packaging macOS. It is a bit of vacuum, not sure when it will be updated. It should work with the version from qgis-deps, but e.g. conda builds are using different...

**Comment by PeterPetrik** [comment]
it is hard to review, why they are so much style changes? have we changed astyle settings (they need to be same as QGIS one)? @vcloarec

**Comment by vcloarec** [comment]
> it is hard to review, why they are so much style changes? have we changed astyle settings (they need to be same as QGIS one)? @vcloarec

It is not style changes, it is a trick to increase test coverage. As I has said, there were a drop of test coverage because of the GRIB test changes. So to return above 90% coverage, I needed to use this trick: set on only one line the no tested if/thrown exception instead of 2 lines.

File: tests/test_gdal_grib.cpp [hunk 1]
```diff
@@ -211,7 +211,11 @@ TEST( MeshGdalGribTest, ScalarFileWithUComponent )
   ASSERT_EQ( 115680, count );
 
   double value = getValue( ds, 1600 );
-  EXPECT_DOUBLE_EQ( -0.818756103515625, value );
+#if defined( GDAL_VERSION_NUM ) && GDAL_VERSION_NUM< GDAL_COMPUTE_VERSION(3,4,0) //https://github.com/lutraconsulting/MDAL/issues/391
+  EXPECT_DOUBLE_EQ( -0.818756103515625, value ); //until GDAL >= 4.3 is used by macos see https://github.com/lutraconsulting/MDAL/pull/439
```
Comment (PeterPetrik) [inline tests/test_gdal_grib.cpp:215]: I think the comment can be safely deleted

**Review by PeterPetrik — COMMENTED** [review]
can you please revert the styling changes? Hiding the problem (too little coverage) is not good. We can change the limit (90%) in coveralls instead (to 85 or so)

**Comment by vcloarec** [comment]
@PeterPetrik  coverage trick removed.

**Comment by PeterPetrik** [comment]
are windows tests meant to fail? @vcloarec

**Comment by vcloarec** [comment]
> are windows tests meant to fail? @vcloarec

fixed

**Review by PeterPetrik — APPROVED** [review]

**Comment by PeterPetrik** [comment]
thanks
