### PR TITLE
Fix loading of selafin files 

### LINKED ISSUE #276: Some Selafin files fail to load
Thanks for bringing mesh support to QGIS. This will help us in in our workflow around Telemac2D.

Unfortunately many of our selafin files fail to open in QGIS using the add mesh layer functionality. This was tested with the just released 3.14 under Ubuntu 18.04 and 20.04. Some files that cannot be opened with mdal can be opened with the ogr driver but are distorted.

We use different tools to create selafind (double precision) files.

This is an overview of working/non working selafind meshes:

1) preprocessing using BlueKenue (V3.9.5): files can be opened in QGIS as a mesh layer
2) preprocessing using Janet (V2.24): files cannot be opened in QGIS as a mesh layer
3) outputfile telemac2d (Vv7p2r0) with model preprocessed by BlueKenue: files cannot be opened in QGIS as a mesh layer
4) outputfile telemac2d (Vv7p2r0) with model preprocessed by Janet: files cannot be opened in QGIS as a mesh layer

Below is some logging information from QGIS when started from terminal

case 1)

    ../../src/app/qgisapp.cpp:5539 : (addMeshLayerPrivate) [61617ms] completeBaseName: test_sd_1

case 2)

    ../../src/app/qgisapp.cpp:5539 : (addMeshLayerPrivate) [48251ms] completeBaseName: test_sd_2
    ERROR 4: `test_sd_2.slf' not recognized as a supported file format.
    ERROR 4: `test_sd_2.slf' not recognized as a supported file format.
    ERROR 4: `test_sd_2.slf' not recognized as a supported file format.
    ERROR 4: `test_sd_2.slf' not recognized as a supported file format.
    ERROR: Status 3: Unable to load mesh (null)

case 3 and 4)

    ../../src/app/qgisapp.cpp:5539 : (addMeshLayerPrivate) [18895ms] completeBaseName: test_sd_4
    ERROR: Status 3: Driver: SELAFIN: File format problem while reading double array
    ERROR 4: `test_sd_4.slf' not recognized as a supported file format.
    ERROR 4: `test_sd_4.slf' not recognized as a supported file format.
    ERROR: Status 3: Unable to load mesh (null)

On request we can provide additional information and try to create example files.

### PR DESCRIPTION
**Pull request by vcloarec**
fix #276

### CODE REVIEW

File: mdal/frmts/mdal_selafin.cpp [hunk 1]
```diff
@@ -49,7 +49,22 @@ void MDAL::SelafinFile::initialize()
   mFileSize = mIn.tellg();
   mIn.seekg( 0, mIn.beg );
 
-  mIsNativeLittleEndian = MDAL::isNativeLittleEndian();
+  mChangeEndianness = MDAL::isNativeLittleEndian();
+
+  //Check if need to change the endianness
+  // read first size_t that has to be 80
+  size_t firstInt = readSizet();
```
Comment (PeterPetrik) [inline mdal/frmts/mdal_selafin.cpp:56]: can we rename readSizet -> readSizeT

File: mdal/frmts/mdal_selafin.cpp [hunk 2]
```diff
@@ -49,7 +49,22 @@ void MDAL::SelafinFile::initialize()
...
+  mIn.seekg( 0, mIn.beg );
+  if ( firstInt != 80 )
+  {
+    mChangeEndianness = !mChangeEndianness;
+    //Retry
+    firstInt = readSizet();
+    if ( firstInt != 80 )
+      throw MDAL::Error( MDAL_Status::Err_UnknownFormat, "File " + mFileName + " could not be open" );
+    mIn.seekg( 0, mIn.beg );
+  }
```
Comment (PeterPetrik) [inline mdal/frmts/mdal_selafin.cpp:66]: can you please move all this code (lines 52-66) to a new local function `void determineEndianness()`

File: tests/data/slf/README.TXT [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+ - US="friction velocity  "
+
+
+test_sd_8
+---------
+
+created with: Janet (v2.24.00)
+number of timesteps: 1
+parameters: X, Y, B
+comment: this file contains 5 not connected meshes
```
Comment (PeterPetrik) [inline tests/data/slf/README.TXT:45]: remove, file not part of the test suite

File: tests/data/slf/README.TXT [hunk 4]
```diff
@@ -0,0 +1,45 @@
+Some information about the failing selafin files
+================================================
+
+all files
+---------
+
+format: double precision floating point
+projectsion: EPSG 25832
```
Comment (PeterPetrik) [inline tests/data/slf/README.TXT:8]: typo: chnage to crs

File: tests/data/slf/README.TXT [hunk 5]
```diff
@@ -0,0 +1,45 @@
+Some information about the failing selafin files
+================================================
```
Comment (PeterPetrik) [inline tests/data/slf/README.TXT:2]: remove, not valid information

File: mdal/frmts/mdal_selafin.cpp (hunk 2 above)
Comment (vcloarec) [reply mdal/frmts/mdal_selafin.cpp:66]: not sure it is a good idea and I don't see good reason because this code is used only from here. This code has to be executed from the beginning of the file and will change the position in the file if it is called from else where. In the initialize() method, no risk of an unwanted position change in the file.
