### PR TITLE
hecras: fix version 6.0 and wet/dry faces

### LINKED ISSUE #333: Mesh Hec Ras 6.0
New version of Hec Ras (6.0),  new hdf file doesn't work in Qgis

[Prueba.p01.zip](https://github.com/lutraconsulting/MDAL/files/5736316/Prueba.p01.zip)

### PR DESCRIPTION
**Pull request by vcloarec**
fix #333 
New format  is very similar but the dataset group are not exactly the same (Depth and shear stress are now optional)

There are also optional dataset groups that are not yet supported by MDAL.

This PR fix also the comparison for wet/dry faces.

### CODE REVIEW

File: mdal/frmts/mdal_hec2d.cpp [hunk 1]
```diff
@@ -398,7 +407,16 @@ std::shared_ptr<MDAL::MemoryDataset2D> MDAL::DriverHec2D::readElemOutput( const
...
 
-    HdfDataset dsVals = openHdfDataset( gFlowAreaRes, rawDatasetName );
+    HdfDataset dsVals;
+    try
+    {
+      dsVals = openHdfDataset( gFlowAreaRes, rawDatasetName );
+    }
+    catch ( MDAL::Error )
+    {
+      return nullptr;
```
Comment (PeterPetrik) [inline mdal/frmts/mdal_hec2d.cpp:417]: function returns void

File: mdal/frmts/mdal_hec2d.cpp [hunk 2]
```diff
@@ -431,7 +449,7 @@ std::shared_ptr<MDAL::MemoryDataset2D> MDAL::DriverHec2D::readElemOutput( const
             {
               assert( bed_elevation );
               double bed_elev = bed_elevation->scalarValue( eInx );
-              if ( std::isnan( bed_elev ) || fabs( bed_elev - val ) > eps ) // change from bed elevation
+              if ( std::isnan( bed_elev ) || fabs( val - bed_elev ) > ( val + bed_elev )*eps )  // change from bed elevation
```
Comment (PeterPetrik) [inline mdal/frmts/mdal_hec2d.cpp:452]: not sure if I understand this comparison

File: tests/test_hec2d.cpp [hunk 3]
```diff
@@ -392,8 +392,8 @@ TEST( MeshHec2dTest, model_505 )
   count = MDAL_D_valueCount( ds );
   ASSERT_EQ( 73, count );
 
-  value = getValue( ds, 10 );
-  EXPECT_DOUBLE_EQ( 33.000003814697266, value );
+  value = getValue( ds, 50 );
+  EXPECT_TRUE( MDAL::equals( 34.785, value, 0.001 ) );
```
Comment (PeterPetrik) [inline tests/test_hec2d.cpp:396]: why the value changed?

File: mdal/frmts/mdal_hec2d.cpp (hunk 2 above)
Comment (vcloarec) [reply mdal/frmts/mdal_hec2d.cpp:452]: epsilon is the difference between 1.0 and the next value representable by the floating-point

For a float epsilon # 0.000000X 
To compare float (7 signifiant digits) that are not next to 1.0, need to transform epsilon to give it the order of magnitde of the compared float. 
Several way can be used depending on context, here the sum is enought.

File: mdal/frmts/mdal_hec2d.cpp (hunk 1 above)
Comment (vcloarec) [reply mdal/frmts/mdal_hec2d.cpp:417]: std::shared_ptr<MDAL::MemoryDataset2D> is not void.
but make think it will be better to throw a exception outside this method if this is bed elevation

File: tests/test_hec2d.cpp (hunk 3 above)
Comment (vcloarec) [reply tests/test_hec2d.cpp:399]: with dry/wet fixed, getValue( ds, 10 ) = NaN, 
but better to keep the test on NaN and add a test to not NaN

**Review by PeterPetrik — APPROVED** [review]

**Comment by vcloarec** [comment]
backport to 0.7? Same reasons than #320

**Comment by PeterPetrik** [comment]
@saberraz ?

**Comment by saberraz** [comment]
Why not?! :)
